// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Fullscreen","status":true,"description":"Starts the game in fullscreen","parameters":{}},
{"name":"MovieManager","status":false,"description":"動画管理プラグイン","parameters":{}},
{"name":"MoviePicture","status":false,"description":"動画のピクチャ表示プラグイン","parameters":{"movieVolumeType":"none","autoEraseOnEnd":"true","webmExt":"","mp4Ext":""}},
{"name":"视频管理MovieManager","status":false,"description":"動画管理プラグイン","parameters":{}}
];
